version: '3'
services:
  app:
    container_name: nest-app
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - MONGO_URL=mongodb://mongo:27017/organization-app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo-data:
