version: '3'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestjs-db
      - JWT_SECRET=your_jwt_secret

  mongo:
    image: mongo:latest
    container_name: nestjs-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
